#demo 1
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  slack: circleci/slack@4.6.2
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          post-steps:
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots
      # In the event the deployment has failed, alert the engineering team
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@EngineeringTeam"
      # When there is a successful deployment, send a notification with a different template.
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1